@extends('backend.master')
@section('content')

<style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #333;
            margin: 0;
            padding: 0;
            background-color: #f2f4f7;
        }
        .container {
            width: 80%;
            margin: 20px auto;
            padding: 20px;
            border-radius: 12px;
            background-color: #ffffff;
            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.1);
        }
        h1 {
            text-align: center;
            color: #007bff;
            margin-bottom: 20px;
            font-size: 24px;
            border-bottom: 2px solid #007bff;
            padding-bottom: 10px;
        }
        .summary {
            font-size: 18px;
            font-weight: bold;
            text-align: center;
            color: #333;
            margin: 20px 0;
        }
        .details {
            font-size: 16px;
            color: #555;
            text-align: center;
            margin-bottom: 20px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 14px;
            color: #888;
        }
        .footer a {
            color: #007bff;
            text-decoration: none;
        }
        .footer a:hover {
            text-decoration: underline;
        }
    </style>

    <div class="container">
        <h1>Summary Report</h1>
        
        <div class="summary">
            Total Employees: {{ $totalEmployees }}<br>
            Total Salary: {{ number_format($totalSalary, 2) }}
        </div>
        
        <div class="details">
            <p>Report generated on: {{ now()->format('F j, Y') }}</p>
            <p>Generated by: ATI LIMITED</p>
        </div>
        
        <div class="footer">
            For more details, visit our <a href="https://www.atilimited.net/">website</a>.
        </div>
    </div>
@endsection